#!/bin/bash

APP_PATH="/Library/Application Support/WLAN/StatusBarApp.app"
CP_PATH="/Library/Application Support/WLAN/Icons/"
RES_PATH="/Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources/"

echo
echo "=========================================================================="
echo "Choosing Dark, Light or Blue Icons Mode will apply to set!"
echo "=========================================================================="
echo "Select one your choice :" 
echo
echo "1 = Dark Icons"
echo "2 = Light Icons"
echo "3 = Blue Icons"
echo "Q = Exit"
echo
read -p "Selected : " answer
case ${answer:0:1} in
	1 )
		sudo cp -rf "$CP_PATH"blackicns/* "$RES_PATH"
		killall StatusBarApp
	;;
	2 )
		sudo cp -rf "$CP_PATH"whiteicns/* "$RES_PATH"
		killall StatusBarApp
	;;
	3 )
		sudo cp -rf "$CP_PATH"blueicns/* "$RES_PATH"
		killall StatusBarApp
	;;
	Q )
		exit
	;;
esac
echo "==============================="
echo "Restart StatusBarApp..."
echo "==============================="
sleep 5
open "$APP_PATH"
exit
